buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

group = 'com.github.apexiotiver-gif'
version = '1.0.2'

android {
    namespace 'mts.com.proxy'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    sourceSets {
        main {
            manifest.srcFile 'libil2cpp-replacer-v1.0.0/AndroidManifest.xml'
            res.srcDirs = ['libil2cpp-replacer-v1.0.0/res']
            java.srcDirs = ['.']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.apexiotiver-gif'
            artifactId = 'libil2cpp-replacer-v1.0.0'
            version = '1.0.2'

            afterEvaluate {
                artifact("$buildDir/outputs/aar/${project.name}-release.aar")
            }
        }
    }
}
